insert into ekipa (ime, kratica) values ('Atlanta Hawks', 'ATL');
insert into ekipa (ime, kratica) values ('Boston Celtics', 'BOS');
insert into ekipa (ime, kratica) values ('Brooklyn Nets', 'BRK');
insert into ekipa (ime, kratica) values ('Charlotte Hornets', 'CHO');
insert into ekipa (ime, kratica) values ('Chicago Bulls', 'CHI');
insert into ekipa (ime, kratica) values ('Cleveland Cavaliers', 'CLE');
insert into ekipa (ime, kratica) values ('Dallas Mavericks', 'DAL');
insert into ekipa (ime, kratica) values ('Denver Nuggets', 'DEN');
insert into ekipa (ime, kratica) values ('Detroit Pistons', 'DET');
insert into ekipa (ime, kratica) values ('Golden State Warriors', 'GSW');
insert into ekipa (ime, kratica) values ('Houston Rockets', 'HOW');
insert into ekipa (ime, kratica) values ('Indiana Pacers', 'IND');
insert into ekipa (ime, kratica) values ('LA Clippers', 'LAC');
insert into ekipa (ime, kratica) values ('Los Angeles Lakers', 'LAL');
insert into ekipa (ime, kratica) values ('Memphis Grizzlies', 'MEM');
insert into ekipa (ime, kratica) values ('Miami Heat', 'MIA');
insert into ekipa (ime, kratica) values ('Milwaukee Bucks', 'MIL');
insert into ekipa (ime, kratica) values ('Minnesota Timberwolves', 'MIN');
insert into ekipa (ime, kratica) values ('New Orleans Pelicans', 'NOP');
insert into ekipa (ime, kratica) values ('New York Knicks', 'NYK');
insert into ekipa (ime, kratica) values ('Oklahoma City Thunder', 'OKC');
insert into ekipa (ime, kratica) values ('Orlando Magic', 'ORL');
insert into ekipa (ime, kratica) values ('Philadelphia 76ers', 'PHI');
insert into ekipa (ime, kratica) values ('Phoenix Suns', 'PHX');
insert into ekipa (ime, kratica) values ('Portland Trail Blazers', 'POR');
insert into ekipa (ime, kratica) values ('Sacramento Kings', 'SAC');
insert into ekipa (ime, kratica) values ('San Antonio Spurs', 'SAS');
insert into ekipa (ime, kratica) values ('Toronto Raptors', 'TOR');
insert into ekipa (ime, kratica) values ('Utah Jazz', 'UTA');
insert into ekipa (ime, kratica) values ('Washington Wizards', 'WAS');
